language: csharp
solution: MediaManager.sln
install:
  - nuget restore MediaManager.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MediaManager.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./MediaManager.Tests/bin/Release/Travis.Tests.dll
